/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author joaom
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelLateral = new javax.swing.JPanel();
        PanPrimeDrive = new javax.swing.JPanel();
        LabPrimeDrive = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        PanConfiguracoes = new javax.swing.JPanel();
        LabIconeConfiguracoes = new javax.swing.JLabel();
        LabConfiguracoes = new javax.swing.JLabel();
        PanFeedback = new javax.swing.JPanel();
        LabIconeFeedback = new javax.swing.JLabel();
        LabFeedback = new javax.swing.JLabel();
        PanReservas = new javax.swing.JPanel();
        LabIconeReservas = new javax.swing.JLabel();
        LabReservas = new javax.swing.JLabel();
        PanelNovoAluguel = new javax.swing.JPanel();
        LabIconeNovoAluguel = new javax.swing.JLabel();
        LabNovoAluguel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelLateral.setBackground(new java.awt.Color(51, 51, 51));
        PainelLateral.setForeground(new java.awt.Color(51, 51, 51));
        PainelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanPrimeDrive.setBackground(new java.awt.Color(51, 51, 51));
        PanPrimeDrive.setForeground(new java.awt.Color(51, 51, 51));
        PanPrimeDrive.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabPrimeDrive.setBackground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        LabPrimeDrive.setForeground(new java.awt.Color(255, 255, 255));
        LabPrimeDrive.setText("Prime Drive");
        PanPrimeDrive.add(LabPrimeDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 30));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aluguel de carros");
        PanPrimeDrive.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, 30));

        PainelLateral.add(PanPrimeDrive, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 350, 80));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        PainelLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 300, 10));

        PanConfiguracoes.setBackground(new java.awt.Color(70, 70, 70));
        PanConfiguracoes.setForeground(new java.awt.Color(70, 70, 70));
        PanConfiguracoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabIconeConfiguracoes.setBackground(new java.awt.Color(255, 255, 255));
        LabIconeConfiguracoes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabIconeConfiguracoes.setForeground(new java.awt.Color(255, 255, 255));
        PanConfiguracoes.add(LabIconeConfiguracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, -1));

        LabConfiguracoes.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LabConfiguracoes.setForeground(new java.awt.Color(255, 255, 255));
        LabConfiguracoes.setText("Configurações");
        PanConfiguracoes.add(LabConfiguracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        PainelLateral.add(PanConfiguracoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 350, 80));

        PanFeedback.setBackground(new java.awt.Color(70, 70, 70));
        PanFeedback.setForeground(new java.awt.Color(70, 70, 70));
        PanFeedback.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabIconeFeedback.setBackground(new java.awt.Color(255, 255, 255));
        LabIconeFeedback.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabIconeFeedback.setForeground(new java.awt.Color(255, 255, 255));
        PanFeedback.add(LabIconeFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, -1));

        LabFeedback.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LabFeedback.setForeground(new java.awt.Color(255, 255, 255));
        LabFeedback.setText("FeedBack");
        PanFeedback.add(LabFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        PainelLateral.add(PanFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 350, 80));

        PanReservas.setBackground(new java.awt.Color(70, 70, 70));
        PanReservas.setForeground(new java.awt.Color(70, 70, 70));
        PanReservas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabIconeReservas.setBackground(new java.awt.Color(255, 255, 255));
        LabIconeReservas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabIconeReservas.setForeground(new java.awt.Color(255, 255, 255));
        PanReservas.add(LabIconeReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, -1));

        LabReservas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LabReservas.setForeground(new java.awt.Color(255, 255, 255));
        LabReservas.setText("Minhas Reservas");
        PanReservas.add(LabReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        PainelLateral.add(PanReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 80));

        PanelNovoAluguel.setBackground(new java.awt.Color(70, 70, 70));
        PanelNovoAluguel.setForeground(new java.awt.Color(70, 70, 70));
        PanelNovoAluguel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabIconeNovoAluguel.setBackground(new java.awt.Color(255, 255, 255));
        LabIconeNovoAluguel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabIconeNovoAluguel.setForeground(new java.awt.Color(255, 255, 255));
        PanelNovoAluguel.add(LabIconeNovoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 30, -1));

        LabNovoAluguel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        LabNovoAluguel.setForeground(new java.awt.Color(255, 255, 255));
        LabNovoAluguel.setText("Nova Reserva");
        PanelNovoAluguel.add(LabNovoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        PainelLateral.add(PanelNovoAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(PainelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabConfiguracoes;
    private javax.swing.JLabel LabFeedback;
    private javax.swing.JLabel LabIconeConfiguracoes;
    private javax.swing.JLabel LabIconeFeedback;
    private javax.swing.JLabel LabIconeNovoAluguel;
    private javax.swing.JLabel LabIconeReservas;
    private javax.swing.JLabel LabNovoAluguel;
    private javax.swing.JLabel LabPrimeDrive;
    private javax.swing.JLabel LabReservas;
    private javax.swing.JPanel PainelLateral;
    private javax.swing.JPanel PanConfiguracoes;
    private javax.swing.JPanel PanFeedback;
    private javax.swing.JPanel PanPrimeDrive;
    private javax.swing.JPanel PanReservas;
    private javax.swing.JPanel PanelNovoAluguel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
